version: '3'
services:
  db:
    image: mysql:5.6 # DBのイメージは MySQL 5.6 を使用
    environment:
      MYSQL_ROOT_PASSWORD: password # 必要に応じて変更する
      MYSQL_DATABASE: root
    ports:
      - "3308:3306" # ホストの3008にアクセスしたら、コンテナの3006につなげる

  web:
    build: . # カスタムDockerイメージをプロジェクトルートフォルダでビルドする
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/mind_memo
    ports:
      - "3002:3000" # ホストの3001にアクセスしたら、コンテナの3000につなげる
    links:
      - db
